### ISSUE TITLE
Alterar o tema deixando com esquema de cores da versão 1.3.23

### ISSUE THREAD

**Issue by consultormicrosiga** [totvs/tds-vscode#1217]
**Is your feature request related to a problem? Please describe.**
Voltar o esquema de cores da sintaxe do código igual a versão 1.3.23, esse novo esquema de cores na sintaxe me incomoda muito, a ponto de usar a extensão do Totvs Developer desatualizada.

**Describe the solution you'd like**
Uma solução de manter a extensão atualizada, na versão 2.0.5 as com a sintaxe de cores da versão 1.3.23

**Describe alternatives you've considered**
A única alternativa que encontrei foi utilizar a versão 1.3.23, ou seja, com a extensão desatualizada.

**Additional context**
vejam o print, como eu preciso que fique... 

![cores vscode](https://github.com/totvs/tds-vscode/assets/72586861/f3b78caa-0490-4424-a445-ad649ba3b4ad)

**Comment by consultormicrosiga** [comment]
boa tarde @DanielYampolschi

Não é o meu VSCODE, meus outros colegas sofrem com essa mudança também, todos voltaram para versão 1.3.23

Até a versão 1.3.23 o tema de cores do TOTVS Developer Studio era muito bom, a partir da 2.0.2 veio com esse tema novo, cores estranhas, meu trabalho é analisar e desenvolver código em ADVPL e uso o plugin, vai chegar uma hora que algum recurso vai deixar de funcionar porque está desatualizado... 

Preciso só saber como deixar o plugin atualizado (na versão 2.0.5) nas cores antigas do (1.3.23)

Vejam o print abaixo, siga o caminha e instale a versão mais recente e depois a versão anterior

![vscode](https://github.com/totvs/tds-vscode/assets/72586861/064fb8ac-acf6-4379-8571-4aa43ebb49f6)

**Comment by Smmartinez** [comment]
Bom dia!

Eu tenho apenas a extensão oficial e para mim aparece como relatado ***@***.***


Att.
Sergio Martinez Martinez
 
 



De: "DanielYampolschi" ***@***.***>
Enviada: 2024/03/18 14:12:45
Para: ***@***.***
Cc:  ***@***.***
Assunto:  Re: [totvs/tds-vscode] Alterar o tema deixando com esquema de cores da versão 1.3.23 (Issue #1217)
 

 

Ola @consultormicrosiga, fiz um teste aqui, entrando o mesmo código em na versão mais atual e meu resultado foi como na imagem abaixo.
Portanto, possívelmente o problema não é na extensão, mas sim no seu ambiente.

Qual a versão do plugin você tem instalado?

Caso você tenha alguma outra extensão de AdvPL, essa pode interferir no funcionamento da tds-vscode.
image.png (view on web)

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/totvs/tds-vscode/issues/1217#issuecomment-2004489414", "url": "https://github.com/totvs/tds-vscode/issues/1217#issuecomment-2004489414", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by consultormicrosiga** [comment]
bom dia!

Esse comportamento procede inclusive em uma instalação nova, pegamos um computador com windows e instalamos o VSCODE e somente o plugin da Totvs com a versão mais recente (2.0.5) o esquema de cores é como mencionei, entendo que nenhum teste foi feito por vocês.

Por favor, eu e meus colegas só queremos utilizar o plugin com as cores antigas, só isso, me mostre como fazer...

obs: fiz um teste instalando a versão antiga 1.3.23 e as cores ficaram do jeito que preciso.

![image](https://github.com/totvs/tds-vscode/assets/72586861/7b64ea7e-f6f5-41fa-b502-954121799570)

**Comment by brodao2** [comment]
Senhores,

Essa alteração no esquema de cores, deve-se a implementação de melhoria efetuada na versão [2.0.1](https://github.com/totvs/tds-vscode/blob/master/CHANGELOG.md#vers%C3%A3o-201).

Para customizar as cores, veja [Color Themes](https://code.visualstudio.com/docs/getstarted/themes), mas especificamente [Editor semantic highlighting](https://code.visualstudio.com/docs/getstarted/themes#_editor-semantic-highlighting)

**Comment by DanielYampolschi** [comment]
Ola @consultormicrosiga , realmente com o primeiro exemplo nao foi possível reproduzir, apenas com a segunda imagem, que deu uma pouco mais de contexto, onde foi possível ver que só reproduz entre um "BeginSql" e "EndSql".

Fiz a correção, e na próxima versão já deve ter o Syntax Highlight mais próximo ao que tinha na 1.3.23. Na realidade, até mais completo do que tinha antes (que nao tinha tratamento pra uma série de outras palavras reservadas de SQL)

De qualquer forma, a sugestão do Alan se mantém. Caso você não goste de alguma cor, é possível fazer suas próprias alterações no tema conforme achar melhor seguindo a documentação que ele passou.

**Comment by consultormicrosiga** [comment]
boa tarde @brodao2 e @DanielYampolschi 

Muito obrigado pelos 2 comentários, não consegui criar meu próprio tema ainda, igual da versão 1.3.23, mas vou continuar tentando até conseguir, se vcs tiverem algum layout que eu possa importar no VsCode e ele alterar o tema eu agradeço vocês.

Tenho certeza que existem desenvolvedores que gostam da cor, não acho que estejam errados, mas particularmente eu e meus colegas ficamos muito tempo olhando pro VSCode e não gostamos, tanto que voltamos o plugin para versão 1.3.23 que tem um esquema de cor muito mais agradável...
