### ISSUE TITLE
Protheus ao compilar Files/Folder

### ISSUE THREAD

**Issue by mmateusmedeiros** [totvs/tds-vscode#329]
Ao realizar a compilação do projeto completo através da opção compilar files/folder, conforme abaixo. Após a finalização da compilação, acesso as rotinas após aplicação no ambiente compilado, e o mesmo retorna que a função não está compilada. Isso não ocorre se eu compilar funções individualmente.

SO: Windows 10. 
Versão Protheus: 12.1.25 
![vscode](https://user-images.githubusercontent.com/8399045/78032498-7ddb2500-733b-11ea-9e67-dea4943ca3bf.png)

**Comment by lwtnb-wrk** [comment]
@mmateusmedeiros Não reproduzi seu problema em nossos ambientes.
Poderia adicionar as linhas:
    "totvsLanguageServer.launch.args": [
        "--log-file=totvsls.log",
        "--record=totvsls"
    ],
Ao seu settings.json , reiniciar seu TDS VS Code e repetir as operações?
Nos envie o arquivo "totvsls.log" para que possamos analisar e tentar encontrar o problema.
Grato

**Comment by mmateusmedeiros** [comment]
@lwtnb-wrk 
Segue o arquivo de log pós compilação. 

O relato é no Log apresenta que todos os arquivos foram compilados com sucesso, porém ao acessar a aplicação e acessar as rotinas compiladas a mesma não reconhece a compilação e retorna que os códigos fontes não existem. 

Grato.
[totvsls.log](https://github.com/totvs/tds-vscode/files/4415059/totvsls.log)

**Comment by lwtnb-wrk** [comment]
@mmateusmedeiros Ocorreu algum erro em um dos arquivos compilados, pois no final do totvsls.log existe a mensagem: Aborting end build (rollback changes). que reverte todos os arquivos compilados. Mas não existe um erro claro no log (Vou rever isso)... 
Enfim, devem existir mais dois arquivos totvsls_in.log e totvsls_out.log gerados. Poderia envia-los tambem?
Grato

**Comment by mmateusmedeiros** [comment]
@lwtnb-wrk 

Processo realizados novamente, e realmente ocorreu um problema antes do final da compilação ( imagem anexo )
[totvsls.log](https://github.com/totvs/tds-vscode/files/4415438/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/4415439/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/4415440/totvsls_out.log)
![vscode](https://user-images.githubusercontent.com/8399045/78143477-ba268800-7404-11ea-9d78-c8922a2587a6.png)

**Comment by lwtnb-wrk** [comment]
@mmateusmedeiros O erro da imagem anterior está ocorrendo todas vez ou aconteceu pontualmente? Enfim pela mensagem parece ser algo do VS Code mesmo, mas pode ser por estarmos gerando/exibindo muitas mensagens no Output e as notificações do canto inferior direito.
Bom pelos logs identifiquei que o problema ocorre com CAPC019.PRW que não tem conteúdo valido. Provavelmente é um fonte todo comentado que apos o pre-processamento fica vazio. Remova esse fonte ou deixe ao menos uma linha de include genérica como:
#include "protheus.ch"
Esse erro não foi exibido na visão Problems??

**Comment by mmateusmedeiros** [comment]
Com relação ao erro da imagem, todas as vezes que executo a compilação da pasta com todos os códigos fontes acontece o problema.

Irei analisar o capc019, mas o mesmo tem conteúdo, até porquê se eu compilar o mesmo individualmente o mesmo compila.

**Comment by Smmartinez** [comment]
Boa tarde!
esta utilizando o ultimo Binário com SSL?
Tentar tirar a segurança e cria uma nova conexão e tentar compilar


Att.
Sergio Martinez Martinez
 
 



De: "mmateusmedeiros" <notifications@github.com>
Enviada: 2020/04/01 13:48:00
Para: tds-vscode@noreply.github.com
Cc:  subscribed@noreply.github.com
Assunto:  Re: [totvs/tds-vscode] Protheus ao compilar Files/Folder (#329)
 

 

Com relação ao erro da imagem, todas as vezes que executo a compilação da pasta com todos os códigos fontes acontece o problema.

Irei analisar o capc019, mas o mesmo tem conteúdo, até porquê se eu compilar o mesmo individualmente o mesmo compila.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/totvs/tds-vscode/issues/329#issuecomment-607364354", "url": "https://github.com/totvs/tds-vscode/issues/329#issuecomment-607364354", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by mmateusmedeiros** [comment]
Ok. 
Obrigado @Smmartinez.

**Comment by lwtnb-wrk** [comment]
@mmateusmedeiros Alteramos a exibição das informações de compilação no console e "Compilation Result" (tabela com informacoes dos arquivos compilado) para exibir apenas os arquivos com erros que impedem a continuidade do processo.
Estas alterações estarão disponiveis na proxima atualização.
Por curiosidade, seria possivel me enviar o "CAPC019.PRW" ?

**Comment by mmateusmedeiros** [comment]
@lwtnb-wrk estou acompanhando as atualizações. 

Segue anexo o solicitado. 

[CAPC019.zip](https://github.com/totvs/tds-vscode/files/4494860/CAPC019.zip)

**Comment by lwtnb-wrk** [comment]
@mmateusmedeiros Esse CAPC019.prw esta dando um erro na linha 1556 aqui. "variable is not Local"
Esse tipo de erro esta fora do padrão e tivemos que alterar o "parser" de retorno do Appre.
A atualização tambem deve estar na proxima release, mas veja que deve ser esse o seu problema.
