### ISSUE TITLE
Objeto sem detalhamento no debug

### ISSUE THREAD

**Issue by EvandroFBL** [totvs/tds-vscode#586]
**Describe the bug**
Durante o Debug, o detalhamento do objeto não está funcionando. Nem ao passar o mouse em cima nem no watch. O único jeito de ver o detalhamento do objeto e colocando ele diretamente no watch, mesmo assim, se tiver um outro objeto dentro dele, o objeto é apenas listado.

**To Reproduce**
Qualquer debug

**Screenshots**
![image](https://user-images.githubusercontent.com/8302095/100282917-40bb4700-2f4b-11eb-8a46-d4df872db110.png)

**Desktop (please complete the following information):**
 - OS/Architecture: Windows 10 versão 2004 64 bits

**Appserver (please complete the following information):**
 - Build (with date): 7.00.191205P-20200724 - 64 bits
 - OS/Architecture: Windows 10 versão 2004 64 bits
 - Build Version 19.3.0.6_RC7

**Comment by lwtnb-wrk** [comment]
@EvandroFBL A principio este problema já foi corrigido e a correção sairá na próxima atualização.
Mas para termos certeza, poderia anexar um fonte AdvPL com algum exemplo simples da ocorrência assim com um vídeo apresentando o problema?

**Comment by lwtnb-wrk** [comment]
Geramos um VSIX versão 1.2.1 que está em Pré Release (Draft) em https://github.com/totvs/tds-vscode/releases/tag/1.2.1
Se quiserem/puderem baixar e instalar manualmente este VSIX para avaliar se o seu problema relatado foi solucionado, favor nos informar se está corrigido ou não para que possamos realizar a liberação oficial.
Para instalar manualmente o VSIX baixem do link acima e na aba de "Extensões" do VS Code clique em "..." e selecione "Install from VSIX" e apontem para o arquivo baixado.

**Comment by Smmartinez** [comment]
Boa tarde!
Teste aqui e tudo funcionando como o esperado.


Att.
Sergio Martinez Martinez
 
 



De: "lwtnb-wrk" <notifications@github.com>
Enviada: 2020/11/26 17:50:25
Para: tds-vscode@noreply.github.com
Cc:  subscribed@noreply.github.com
Assunto:  Re: [totvs/tds-vscode] Objeto sem detalhamento no debug (#586)
 

 

Geramos um VSIX versão 1.2.1 que está em Pré Release (Draft) em https://github.com/totvs/tds-vscode/releases/tag/1.2.1
Se quiserem/puderem baixar e instalar manualmente este VSIX para avaliar se o seu problema relatado foi solucionado, favor nos informar se está corrigido ou não para que possamos realizar a liberação oficial.
Para instalar manualmente o VSIX baixem do link acima e na aba de "Extensões" do VS Code clique em "..." e selecione "Install from VSIX" e apontem para o arquivo baixado.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/totvs/tds-vscode/issues/586#issuecomment-734473520", "url": "https://github.com/totvs/tds-vscode/issues/586#issuecomment-734473520", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]
