### ISSUE TITLE
Erro Cannot overwrite TOTVS programs (MATR968.PRW)compile

### ISSUE THREAD

**Issue by DouglasCitopharma** [totvs/tds-vscode#601]
Bom dia!

Baixei o arquivo fonte padrão MATR968 e estou tentando compilá-lo em meu ambiente. Estou tendo o seguinte problema ao tentar compilá-lo:

Cannot overwrite TOTVS programs (MATR968.PRW)compile

Atualizei o meu TDS, renomeei a função para User Function MATR968(), já atualizei a minha pasta include (.ch) e tentei também excluir o fonte do RPO e compilá-lo novamente conforme orientado no TDN. Porém, não obtive sucesso.

Dados do ambiente onde estou compilando:

Dados do Server 

Versão: TOTVS Varejo
Build AppServer: 7.00.191205P-20201029 - 64 bits
Nome do servidor: 108598-PROTHEUS
Sistema operacional: Windows Server 2016
Appserver version: 19.3.1.1
Build DBAccess: 20200606-20201012
Release do RPO:  12.1.025
Release do dicionário: 12.1.025
Local files: ctree
License server: 2014 - 3.2.0
DB DataBase: MSSQL
DB API Build: 20200606-20201012

Versão da Lib:20201123
Data da Lib: 20201130_153311
Commit ID:dafd6a2a9f383c9a31885287d7aaf209b41d5c2c

[matr968.ch.txt](https://github.com/totvs/tds-vscode/files/5679744/matr968.ch.txt)
[matr968.txt](https://github.com/totvs/tds-vscode/files/5679745/matr968.txt)

**Comment by Smmartinez** [comment]
Bom dia!

No fonte não tem mais alguma função como Function nome? se tiver tente colocar STATIC FUNCTION nome e tenta compilar.


Att.
Sergio Martinez Martinez
 
 



De: "DouglasCitopharma" <notifications@github.com>
Enviada: 2020/12/11 11:42:56
Para: tds-vscode@noreply.github.com
Cc:  subscribed@noreply.github.com
Assunto:  [totvs/tds-vscode] Erro Cannot overwrite TOTVS programs (MATR968.PRW)compile (#601)
 

 

Bom dia!

Baixei o arquivo fonte padrão MATR968 e estou tentando compilá-lo em meu ambiente. Estou tendo o seguinte problema ao tentar compilá-lo:

Cannot overwrite TOTVS programs (MATR968.PRW)compile

Atualizei o meu TDS, renomeei a função para User Function MATR968(), já atualizei a minha pasta include (.ch) e tentei também excluir o fonte do RPO e compilá-lo novamente conforme orientado no TDN. Porém, não obtive sucesso.

Dados do ambiente onde estou compilando:

Dados do Server

Versão: TOTVS Varejo
Build AppServer: 7.00.191205P-20201029 - 64 bits
Nome do servidor: 108598-PROTHEUS
Sistema operacional: Windows Server 2016
Appserver version: 19.3.1.1
Build DBAccess: 20200606-20201012
Release do RPO: 12.1.025
Release do dicionário: 12.1.025
Local files: ctree
License server: 2014 - 3.2.0
DB DataBase: MSSQL
DB API Build: 20200606-20201012

Versão da Lib:20201123
Data da Lib: 20201130_153311
Commit ID:dafd6a2a9f383c9a31885287d7aaf209b41d5c2c

matr968.ch.txt
matr968.txt

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/totvs/tds-vscode/issues/601", "url": "https://github.com/totvs/tds-vscode/issues/601", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by DouglasCitopharma** [comment]
Não, as demais funções estão como Static Function

**Comment by lwtnb-wrk** [comment]
@DouglasCitopharma Até onde sei, um fonte padrão não pode ser apagado nem sobrescrito sem uma chave de compilação com permissão para sobrescrever fonte padrão. Esse tipo de chave é de uso exclusivo dentro da TOTVS.
Realmente uma customização deve ser escrita como uma User Function, mas deve estar em um arquivo diferente do original (matr968.prw), pois o original não pode ser sobrescrito. Além disso a chamada original da matr968() deve ser substituida pela u_matr968().
Veja se é este o seu caso e faça os ajustes necessários.

**Comment by DouglasCitopharma** [comment]
Obrigado pelo retorno galera!

Já havia renomeado o fonte, porém o erro persistia. Já havia tentando compilar esse fontes, mas sempre me deparava com algum erro, por fim, consegui excluir alguns registros dele do RPO, alterei o nome do fonte novamente e consegui passar por este erro.

Tive outros problemas com relação à classe que está declarada no mesmo, após comentar as linhas da classe, consegui compilá-lo e aplicar a customização que eu precisava.

Muito obrigado pelo apoio.
