### ISSUE TITLE
Erro ao compilar rdmakes - C2006 - Statement not allowed outside procedure or function

### ISSUE THREAD

**Issue by lufeos** [totvs/tds-vscode#664]
Bom dia!

Estou tendo problemas para compilar os rdmakes (prw) no meu ambiente usando a extensão TOTVS no VSCODE.

VSCODE
Version: 1.55.0 (user setup)
Commit: c185983a683d14c396952dd432459097bc7f757f
Date: 2021-03-30T16:01:55.261Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

TOTVS Extension
---------------------------v---------------------------------------------------
   //////  ////    //////  |  TOTVS Developer Studio for VS-Code
    //    //  //  //       |  Version 1.2.1
   //    //  //  //////    |  TOTVS Technology
  //    //  //      //     |
 //    ////    //////      |  https://github.com/totvs/tds-vscode
 --------------------------^---------------------------------------------------

A conexão com o ambiente está ocorrendo normalmente:

[Info  - 08:14:02] Starting connection to the server 'UPDATE23' (192.168.1.3@41234)
[Info  - 08:14:04] Connection to the server 'UPDATE23' finished.
[Info  - 08:14:09] Starting user 'admin' authentication.
[Info  - 08:14:09] Secure authenticating...
[Info  - 08:14:11] User authenticated successfully.
[Info  - 08:14:11] User 'admin' authentication finished.

Porém ao tentar compilar qualquer RDMAKE, está ocorrendo o erro: (erro-compilar.png)
procedimento utilizado: clico com o botão direito do mouse sobre o nome do arquivo e escolho a opção: Compile File/Folder CTRL+F9 (compilar.png)

Erro: **C2006 - Statement not allowed outside procedure or function appre [50,1]**

No código é destacado a linha: 
Local aArea     := GetArea()

A pasta INCLUDE está atualizada e completa

Tentei utilizando o Windows 10 Pro e também o Windows Server 2016 Standard, em ambos Sistemas Operacionais ocorre o mesmo erro.

Nota: Consigo aplicar normalmente os patchs (PTM), conforme mostra abaixo:

Nota: Os pacotes PTM estou conseguindo compilar normalmente, conforme mostra abaixo:
[Info - 08:23:02] Patch validated without structure problems.
[Info - 08:23:02] Aborting end build (rollback changes).
[Info - 08:23:02] Patch validate finished.
[Info - 08:23:02] Starting build for environment DESENV.
[Info - 08:23:03] Applying patch file: g:/upd_202104/z21-04-05-LIB_LABEL_05042021_P12_LOBO/21-04-05-LIB_LABEL_05042021_P12_LOBO-TTTP120.PTM
[Info - 08:23:09] Patch (21-04-05-LIB_LABEL_05042021_P12_LOBO-TTTP120.PTM) successfully applied.
[Info - 08:23:09] Committing end build.
[Info - 08:23:10] Apply patch finished.

**AppServer**
* TOTVS - Build 7.00.191205P - Jan 14 2021 - 21:11:32 
* Build: 64 bits
* SVN Revision: 29345
* Build Version: 19.3.1.5

**SmartClient** (smartclient-version.png)
* 7.00.191205P-20210108
* 19.3.1.2

![compilar](https://user-images.githubusercontent.com/79984639/113859590-7256e100-977b-11eb-9834-85f7e4fa9291.png)
![erro-compilar](https://user-images.githubusercontent.com/79984639/113859594-73880e00-977b-11eb-9e33-97f7a692381e.png)
![smartclient-version](https://user-images.githubusercontent.com/79984639/113859596-7420a480-977b-11eb-8734-ebe6654309c7.png)
![totvs-extension-installed](https://user-images.githubusercontent.com/79984639/113859598-7420a480-977b-11eb-8c49-f8cab8a8c832.png)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/6271207/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/6271208/totvsls_out.log)
[totvsls20210406.log](https://github.com/totvs/tds-vscode/files/6271209/totvsls20210406.log)

**Comment by Smmartinez** [comment]
Bom dia!

Baixe os includes novamente do portal.
Estava com esse mesmo problema e com a atualização de ontem dos includes resolveu


Att.
Sergio Martinez Martinez
 
 



De: "lufeos" ***@***.***>
Enviada: 2021/04/07 08:30:30
Para: ***@***.***
Cc:  ***@***.***
Assunto:  [totvs/tds-vscode] Erro ao compilar rdmakes - C2006 - Statement not allowed outside procedure or function (#664)
 

 

Bom dia!

Estou tendo problemas para compilar os rdmakes (prw) no meu ambiente usando a extensão TOTVS no VSCODE.

VSCODE
Version: 1.55.0 (user setup)
Commit: c185983a683d14c396952dd432459097bc7f757f
Date: 2021-03-30T16:01:55.261Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

TOTVS Extension
---------------------------v---------------------------------------------------
////// //// ////// | TOTVS Developer Studio for VS-Code
// // // // | Version 1.2.1
// // // ////// | TOTVS Technology
// // // // |
// //// ////// | https://github.com/totvs/tds-vscode
--------------------------^---------------------------------------------------

A conexão com o ambiente está ocorrendo normalmente:

[Info - 08:14:02] Starting connection to the server 'UPDATE23' ***@***.***)
[Info - 08:14:04] Connection to the server 'UPDATE23' finished.
[Info - 08:14:09] Starting user 'admin' authentication.
[Info - 08:14:09] Secure authenticating...
[Info - 08:14:11] User authenticated successfully.
[Info - 08:14:11] User 'admin' authentication finished.

Porém ao tentar compilar qualquer RDMAKE, está ocorrendo o erro: (erro-compilar.png)
procedimento utilizado: clico com o botão direito do mouse sobre o nome do arquivo e escolho a opção: Compile File/Folder CTRL+F9 (compilar.png)

Erro: C2006 - Statement not allowed outside procedure or function appre [50,1]

No código é destacado a linha:
Local aArea := GetArea()

A pasta INCLUDE está atualizada e completa

Tentei utilizando o Windows 10 Pro e também o Windows Server 2016 Standard, em ambos Sistemas Operacionais ocorre o mesmo erro.

Nota: Consigo aplicar normalmente os patchs (PTM), conforme mostra abaixo:

Nota: Os pacotes PTM estou conseguindo compilar normalmente, conforme mostra abaixo:
[Info - 08:23:02] Patch validated without structure problems.
[Info - 08:23:02] Aborting end build (rollback changes).
[Info - 08:23:02] Patch validate finished.
[Info - 08:23:02] Starting build for environment DESENV.
[Info - 08:23:03] Applying patch file: g:/upd_202104/z21-04-05-LIB_LABEL_05042021_P12_LOBO/21-04-05-LIB_LABEL_05042021_P12_LOBO-TTTP120.PTM
[Info - 08:23:09] Patch (21-04-05-LIB_LABEL_05042021_P12_LOBO-TTTP120.PTM) successfully applied.
[Info - 08:23:09] Committing end build.
[Info - 08:23:10] Apply patch finished.

AppServer


	TOTVS - Build 7.00.191205P - Jan 14 2021 - 21:11:32
	Build: 64 bits
	SVN Revision: 29345
	Build Version: 19.3.1.5


SmartClient (smartclient-version.png)


	7.00.191205P-20210108
	19.3.1.2






totvsls_in.log
totvsls_out.log
totvsls20210406.log

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/totvs/tds-vscode/issues/664", "url": "https://github.com/totvs/tds-vscode/issues/664", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by lufeos** [comment]
Olá Sergio Martinez,
Bom dia!

Fiz novamente o download dos includes e dos rdmakes e tudo voltou a funcionar e compilar novamente.

Obrigado pelo retorno e atenção.


At.te,


Luiz.




> Bom dia! Baixe os includes novamente do portal. Estava com esse mesmo problema e com a atualização de ontem dos includes resolveu Att. Sergio Martinez Martinez     De: "lufeos" ***@***.***> Enviada: 2021/04/07 08:30:30 Para: ***@***.*** Cc: ***@***.*** Assunto: [totvs/tds-vscode] Erro ao compilar rdmakes - C2006 - Statement not allowed outside procedure or function (#664)     Bom dia! Estou tendo problemas para compilar os rdmakes (prw) no meu ambiente usando a extensão TOTVS no VSCODE. VSCODE Version: 1.55.0 (user setup) Commit: c185983a683d14c396952dd432459097bc7f757f Date: 2021-03-30T16:01:55.261Z Electron: 11.3.0 Chrome: 87.0.4280.141 Node.js: 12.18.3 V8: 8.7.220.31-electron.0 OS: Windows_NT x64 10.0.19042 TOTVS Extension ---------------------------v--------------------------------------------------- ////// //// ////// | TOTVS Developer Studio for VS-Code // // // // | Version 1.2.1 // // // ////// | TOTVS Technology // // // // | // //// ////// | https://github.com/totvs/tds-vscode --------------------------^--------------------------------------------------- A conexão com o ambiente está ocorrendo normalmente: [Info - 08:14:02] Starting connection to the server 'UPDATE23' ***@***.***) [Info - 08:14:04] Connection to the server 'UPDATE23' finished. [Info - 08:14:09] Starting user 'admin' authentication. [Info - 08:14:09] Secure authenticating... [Info - 08:14:11] User authenticated successfully. [Info - 08:14:11] User 'admin' authentication finished. Porém ao tentar compilar qualquer RDMAKE, está ocorrendo o erro: (erro-compilar.png) procedimento utilizado: clico com o botão direito do mouse sobre o nome do arquivo e escolho a opção: Compile File/Folder CTRL+F9 (compilar.png) Erro: C2006 - Statement not allowed outside procedure or function appre [50,1] No código é destacado a linha: Local aArea := GetArea() A pasta INCLUDE está atualizada e completa Tentei utilizando o Windows 10 Pro e também o Windows Server 2016 Standard, em ambos Sistemas Operacionais ocorre o mesmo erro. Nota: Consigo aplicar normalmente os patchs (PTM), conforme mostra abaixo: Nota: Os pacotes PTM estou conseguindo compilar normalmente, conforme mostra abaixo: [Info - 08:23:02] Patch validated without structure problems. [Info - 08:23:02] Aborting end build (rollback changes). [Info - 08:23:02] Patch validate finished. [Info - 08:23:02] Starting build for environment DESENV. [Info - 08:23:03] Applying patch file: g:/upd_202104/z21-04-05-LIB_LABEL_05042021_P12_LOBO/21-04-05-LIB_LABEL_05042021_P12_LOBO-TTTP120.PTM [Info - 08:23:09] Patch (21-04-05-LIB_LABEL_05042021_P12_LOBO-TTTP120.PTM) successfully applied. [Info - 08:23:09] Committing end build. [Info - 08:23:10] Apply patch finished. AppServer TOTVS - Build 7.00.191205P - Jan 14 2021 - 21:11:32 Build: 64 bits SVN Revision: 29345 Build Version: 19.3.1.5 SmartClient (smartclient-version.png) 7.00.191205P-20210108 19.3.1.2 totvsls_in.log totvsls_out.log totvsls20210406.log — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. [ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "#664", "url": "#664", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]



> Bom dia! Baixe os includes novamente do portal. Estava com esse mesmo problema e com a atualização de ontem dos includes resolveu Att. Sergio Martinez Martinez     De: "lufeos" ***@***.***> Enviada: 2021/04/07 08:30:30 Para: ***@***.*** Cc: ***@***.*** Assunto: [totvs/tds-vscode] Erro ao compilar rdmakes - C2006 - Statement not allowed outside procedure or function (#664)     Bom dia! Estou tendo problemas para compilar os rdmakes (prw) no meu ambiente usando a extensão TOTVS no VSCODE. VSCODE Version: 1.55.0 (user setup) Commit: c185983a683d14c396952dd432459097bc7f757f Date: 2021-03-30T16:01:55.261Z Electron: 11.3.0 Chrome: 87.0.4280.141 Node.js: 12.18.3 V8: 8.7.220.31-electron.0 OS: Windows_NT x64 10.0.19042 TOTVS Extension ---------------------------v--------------------------------------------------- ////// //// ////// | TOTVS Developer Studio for VS-Code // // // // | Version 1.2.1 // // // ////// | TOTVS Technology // // // // | // //// ////// | https://github.com/totvs/tds-vscode --------------------------^--------------------------------------------------- A conexão com o ambiente está ocorrendo normalmente: [Info - 08:14:02] Starting connection to the server 'UPDATE23' ***@***.***) [Info - 08:14:04] Connection to the server 'UPDATE23' finished. [Info - 08:14:09] Starting user 'admin' authentication. [Info - 08:14:09] Secure authenticating... [Info - 08:14:11] User authenticated successfully. [Info - 08:14:11] User 'admin' authentication finished. Porém ao tentar compilar qualquer RDMAKE, está ocorrendo o erro: (erro-compilar.png) procedimento utilizado: clico com o botão direito do mouse sobre o nome do arquivo e escolho a opção: Compile File/Folder CTRL+F9 (compilar.png) Erro: C2006 - Statement not allowed outside procedure or function appre [50,1] No código é destacado a linha: Local aArea := GetArea() A pasta INCLUDE está atualizada e completa Tentei utilizando o Windows 10 Pro e também o Windows Server 2016 Standard, em ambos Sistemas Operacionais ocorre o mesmo erro. Nota: Consigo aplicar normalmente os patchs (PTM), conforme mostra abaixo: Nota: Os pacotes PTM estou conseguindo compilar normalmente, conforme mostra abaixo: [Info - 08:23:02] Patch validated without structure problems. [Info - 08:23:02] Aborting end build (rollback changes). [Info - 08:23:02] Patch validate finished. [Info - 08:23:02] Starting build for environment DESENV. [Info - 08:23:03] Applying patch file: g:/upd_202104/z21-04-05-LIB_LABEL_05042021_P12_LOBO/21-04-05-LIB_LABEL_05042021_P12_LOBO-TTTP120.PTM [Info - 08:23:09] Patch (21-04-05-LIB_LABEL_05042021_P12_LOBO-TTTP120.PTM) successfully applied. [Info - 08:23:09] Committing end build. [Info - 08:23:10] Apply patch finished. AppServer TOTVS - Build 7.00.191205P - Jan 14 2021 - 21:11:32 Build: 64 bits SVN Revision: 29345 Build Version: 19.3.1.5 SmartClient (smartclient-version.png) 7.00.191205P-20210108 19.3.1.2 totvsls_in.log totvsls_out.log totvsls20210406.log — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. [ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "#664", "url": "#664", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]
