### ISSUE TITLE
Erro na compilação - MacOS Big Sur

### ISSUE THREAD

**Issue by FAsouza1** [totvs/tds-vscode#665]
Recentemente comprei um macbook e estou configurando o vscode para trabalhar acessando uma base local em uma outra máquina que tenho em casa (Windows 10). Configurei tudo certo no vscode ( eu acho ), até consegui acessar o smartclient e rodar uma rotina, mas eu não consigo compilar os fontes.
Como não sei muita coisa de macOS, entrei em contato com um amigo que trabalha com esse sistema há mais tempo. Ele disse que pode ser a versão do macOS( Big Sur ), pois ele usa o MacOs ( Catalina ) e o plugin funciona normalmente no vscode dele, então optei por pedir ajuda aqui para não ter que recorrer ao "Downgrade" do sistema.

-----------------------------------------------------------------------------------------------------------------------------
### Essa é a "base teste" que eu to usando pra configurar o vscode
-----------------------------------------------------------------------------------------------------------------------------

<img width="1186" alt="Captura de Tela 2021-04-07 às 10 48 01" src="https://user-images.githubusercontent.com/34289529/113877673-4e04ff80-978f-11eb-9b7a-32ae48e8a6ed.png">

-----------------------------------------------------------------------------------------------------------------------------

### Arquivos de Configuração ( Launch.json e Servers.json )

-----------------------------------------------------------------------------------------------------------------------------

<img width="1680" alt="Captura de Tela 2021-04-07 às 11 20 23" src="https://user-images.githubusercontent.com/34289529/113882076-6119ce80-9793-11eb-8b07-88715e693055.png">

-----------------------------------------------------------------------------------------------------------------------------

### Esse é o erro que está ocorrendo

-----------------------------------------------------------------------------------------------------------------------------

<img width="1680" alt="Captura de Tela 2021-04-07 às 11 06 38" src="https://user-images.githubusercontent.com/34289529/113880189-a3421080-9791-11eb-89f8-c7852180fa1d.png">

**Comment by Smmartinez** [comment]
Bom dia!

Posso dar uma sugestão, cria uma pasta fora da pasta .vscode e coloca esse fonte lá.

Veja se funciona


Att.
Sergio Martinez Martinez
 
 



De: "Filipe Apolinário" ***@***.***>
Enviada: 2021/04/07 11:25:07
Para: ***@***.***
Cc:  ***@***.***
Assunto:  [totvs/tds-vscode] Erro na compilação - MacOS Big Sur (#665)
 

 

Recentemente comprei um macbook e estou configurando o vscode para trabalhar acessando uma base local em uma outra máquina que tenho em casa (Windows 10). Configurei tudo certo no vscode ( eu acho ), até consegui acessar o smartclient e rodar uma rotina, mas eu não consigo compilar os fontes.
Como não sei muita coisa de macOS, entrei em contato com um amigo que trabalha com esse sistema há mais tempo. Ele disse que pode ser a versão do macOS( Big Sur ), pois ele usa o MacOs ( Catalina ) e o plugin funciona normalmente no vscode dele, então optei por pedir ajuda aqui para não ter que recorrer ao "Downgrade" do sistema.


Essa é a "base teste" que eu to usando pra configurar o vscode





Arquivos de Configuração ( Launch.json e Servers.json )





Esse é o erro que está ocorrendo




—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/totvs/tds-vscode/issues/665", "url": "https://github.com/totvs/tds-vscode/issues/665", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by FAsouza1** [comment]
<img width="1680" alt="Captura de Tela 2021-04-07 às 11 37 52" src="https://user-images.githubusercontent.com/34289529/113884894-bfe04780-9795-11eb-9030-a273c65ca8e3.png">

Testei mas não deu certo

**Comment by Smmartinez** [comment]
Esses includes vc baixou faz tempo?


Att.
Sergio Martinez Martinez
 
 



De: "Filipe Apolinário" ***@***.***>
Enviada: 2021/04/07 11:40:21
Para: ***@***.***
Cc:  ***@***.***, ***@***.***
Assunto:  Re: [totvs/tds-vscode] Erro na compilação - MacOS Big Sur (#665)
 

 



Testei mas não deu certo

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.

[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/totvs/tds-vscode/issues/665#issuecomment-814970400", "url": "https://github.com/totvs/tds-vscode/issues/665#issuecomment-814970400", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by FAsouza1** [comment]
Baixei ontem do portal da TOTVS

**Comment by FAsouza1** [comment]
Acabei de ler a issues que 

> Esses includes vc baixou faz tempo? Att. Sergio Martinez Martinez     De: "Filipe Apolinário" ***@***.***> Enviada: 2021/04/07 11:40:21 Para: ***@***.*** Cc: ***@***.***, ***@***.*** Assunto: Re: [totvs/tds-vscode] Erro na compilação - MacOS Big Sur (#665)     Testei mas não deu certo — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. [ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "[#665 (comment)](https://github.com/totvs/tds-vscode/issues/665#issuecomment-814970400)", "url": "[#665 (comment)](https://github.com/totvs/tds-vscode/issues/665#issuecomment-814970400)", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

Acabei de ler a issues que você abriu sobre o problema das includes desse mês... Troquei aqui para uma versão anterior e compilou normal

**Comment by Smmartinez** [comment]
Data do dia 01/04 ou 06/04?


Att.
Sergio Martinez Martinez
 
 



De: "Filipe Apolinário" ***@***.***>
Enviada: 2021/04/07 11:44:37
Para: ***@***.***
Cc:  ***@***.***, ***@***.***
Assunto:  Re: [totvs/tds-vscode] Erro na compilação - MacOS Big Sur (#665)
 

 

Baixei ontem do portal da TOTVS

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.

[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/totvs/tds-vscode/issues/665#issuecomment-814973517", "url": "https://github.com/totvs/tds-vscode/issues/665#issuecomment-814973517", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by FAsouza1** [comment]
> Data do dia 01/04 ou 06/04? Att. Sergio Martinez Martinez     De: "Filipe Apolinário" ***@***.***> Enviada: 2021/04/07 11:44:37 Para: ***@***.*** Cc: ***@***.***, ***@***.*** Assunto: Re: [totvs/tds-vscode] Erro na compilação - MacOS Big Sur (#665)     Baixei ontem do portal da TOTVS — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. [ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "[#665 (comment)](https://github.com/totvs/tds-vscode/issues/665#issuecomment-814973517)", "url": "[#665 (comment)](https://github.com/totvs/tds-vscode/issues/665#issuecomment-814973517)", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

06/04

**Comment by Smmartinez** [comment]
Baixa os includes com a data de 06/04 corrige esse problema!


Att.
Sergio Martinez Martinez
 
 



De: "Filipe Apolinário" ***@***.***>
Enviada: 2021/04/07 11:49:28
Para: ***@***.***
Cc:  ***@***.***, ***@***.***
Assunto:  Re: [totvs/tds-vscode] Erro na compilação - MacOS Big Sur (#665)
 

 


Esses includes vc baixou faz tempo? Att. Sergio Martinez Martinez     De: "Filipe Apolinário" @.> Enviada: 2021/04/07 11:40:21 Para: @. Cc: @., @. Assunto: Re: [totvs/tds-vscode] Erro na compilação - MacOS Big Sur (#665)     Testei mas não deu certo — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. [ { @.": "http://schema.org", @.": "EmailMessage", "potentialAction": { @.": "ViewAction", "target": "#665 (comment)", "url": "#665 (comment)", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { @.": "Organization", "name": "GitHub", "url": "https://github.com&quo
 t; } } ]


Acabei de ler a issues que você abriu sobre o problema das includes desse mês... Troquei aqui para uma versão anterior e compilou normal

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.

[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/totvs/tds-vscode/issues/665#issuecomment-814977196", "url": "https://github.com/totvs/tds-vscode/issues/665#issuecomment-814977196", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by FAsouza1** [comment]
vou testar com a versão nova e ja falo se funcionou

**Comment by FAsouza1** [comment]
> Baixa os includes com a data de 06/04 corrige esse problema! Att. Sergio Martinez Martinez     De: "Filipe Apolinário" ***@***.***> Enviada: 2021/04/07 11:49:28 Para: ***@***.*** Cc: ***@***.***, ***@***.*** Assunto: Re: [totvs/tds-vscode] Erro na compilação - MacOS Big Sur (#665)     Esses includes vc baixou faz tempo? Att. Sergio Martinez Martinez     De: "Filipe Apolinário" @.> Enviada: 2021/04/07 11:40:21 Para: @. Cc: @., @. Assunto: Re: [totvs/tds-vscode] Erro na compilação - MacOS Big Sur (#665)     Testei mas não deu certo — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. [ { @.": "http://schema.org", @.": "EmailMessage", "potentialAction": { @.": "ViewAction", "target": "#665 (comment)", "url": "#665 (comment)", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { @.": "Organization", "name": "GitHub", "url": "https://github.com&quo t; } } ] Acabei de ler a issues que você abriu sobre o problema das includes desse mês... Troquei aqui para uma versão anterior e compilou normal — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. [ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "[#665 (comment)](https://github.com/totvs/tds-vscode/issues/665#issuecomment-814977196)", "url": "[#665 (comment)](https://github.com/totvs/tds-vscode/issues/665#issuecomment-814977196)", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

Baixei as includes novas e compilou corretamente, Muito obrigado pelo auxilio.
